### ISSUE TITLE
Stacktrace on JVM exit when calling .close on server from SignalHandler thread

### ISSUE THREAD

**Issue by ivarref** [clj-commons/aleph#603] opened 2022-06-13 11:26 UTC
Hi and thanks for all the work that is put into this library!

I have a strange issue that only arises when calling `(.close server)` from a `SignalHandler` thread.

Reproducing repo: https://github.com/ivarref/aleph-shutdown-stacktrace

Use `$ ./demo.sh` and after the server is up, hit `Ctrl-C`.
The console will show something like this:
```
2022-06-13 11:20:57:337 +0000 [clojure-agent-send-off-pool-0] [INFO] aleph-shutdown-stacktrace - shutting down in 30 seconds ...
2022-06-13 11:20:57:385 +0000 [main] [INFO] aleph-shutdown-stacktrace - Server listening at 0.0.0.0:8080
^C2022-06-13 11:20:59:508 +0000 [SIGINT handler] [INFO] aleph-shutdown-stacktrace - Received SIGINT
2022-06-13 11:20:59:515 +0000 [SIGINT handler] [INFO] aleph-shutdown-stacktrace - OK shutdown server
2022-06-13 11:20:59:516 +0000 [main] [INFO] aleph-shutdown-stacktrace - About to exit
2022-06-13 11:21:01:522 +0000 [globalEventExecutor-1-1] [WARN] DefaultPromise - An exception was thrown by aleph.netty$wrap_future$reify__4259.operationComplete()
java.lang.ExceptionInInitializerError
        at manifold.deferred.Deferred.success(deferred.clj:399)
        at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:244)
        at manifold.deferred$success_BANG_.invoke(deferred.clj:241)
        at aleph.netty$wrap_future$reify__4259.operationComplete(netty.clj:223)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup$1.operationComplete(MultithreadEventExecutorGroup.java:117)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
        at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:240)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: clojure.lang.PersistentArrayMap
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at clojure.lang.RT.classForName(RT.java:2209)
        at clojure.lang.RT.classForName(RT.java:2218)
        at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:324)
        at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1322)
        at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.read(LispReader.java:220)
        at clojure.lang.LispReader.access$200(LispReader.java:41)
        at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:954)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1398)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1243)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.read(LispReader.java:220)
        at clojure.lang.LispReader.access$200(LispReader.java:41)
        at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1301)
        at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.read(LispReader.java:216)
        at clojure.lang.LispReader.read(LispReader.java:205)
        at clojure.lang.RT.readString(RT.java:1876)
        at clojure.lang.RT.readString(RT.java:1871)
        at manifold.deferred.Deferred$fn__1029.<clinit>(deferred.clj:399)
        ... 19 more
```

If `(.close server)` is called from a regular thread, the JVM exits fine without a stacktrace.

Any ideas?
I think it would be good if calling `.close` in a SignalHandler thread would work without stacktrace exception when the JVM exits.

Thanks and kind regards!

**Comment by KingMob** [comment] 2022-06-15 09:18
Hmmm, well a `ClassNotFoundException` for a core class like PersistentArrayMap usually indicates the thread's classloader isn't Clojure's, but if I read it correctly, that's not the case here. We've had issues in the past with Netty threads' classloaders being unable to execute Clojure callbacks, so Manifold's `thread-factory` explicitly sets the Clojure classloader. But according to the docs, Signal and SignalHandler use a normal java Thread to run the handlers. It seems like the code at https://github.com/clj-commons/aleph/blob/master/src/aleph/netty.clj#L218-L220 should also compensate for it in this case, but maybe that doesn't work as expected here. 

Only real workaround that comes to mind is not do any work in the handler itself, but spin off a clojure thread with `future` that does it. If I'm right about the classloader, that may fix it. But if something is truly funky about the handler's thread, you may not even be able to call `future`.

Regardless, it's hard to know for sure what the fix is without a lot more investigation. Unfortunately, this is a pretty niche request, so I can't really spend more time on it myself. PRs are welcome, though!

**Comment by KingMob** [comment] 2022-06-16 05:37
@ivarref Are you interested in tackling this? If so, I'll leave it up open, but if not, I'm inclined to close it.

**Comment by KingMob** [comment] 2022-06-17 06:34
I'll leave it open for you, then.

I don't actually think it's that common; you're the first person to request it AFAIK. 😄 Generally, web servers are not designed to stop in production, and it's usually less of a big deal if they close messily in local development. 

Regardless, before you go too far down the sun.misc Signal rabbit hole, since you're interested in SIGINT, what about using `java.lang.Runtime.addShutdownHook()` instead? That might be simpler.

**Comment by arnaudgeiser** [comment] 2022-06-17 18:16
I read the outcome quickly without digging.
This is something we do heavily on our side and we are using the following library: https://github.com/pyr/signal/blob/master/src/signal/handler.clj.

May I ask you to give a shot?

**Comment by arnaudgeiser** [comment] 2022-06-17 18:32
For what I worth, here is an example:

```clojure
(ns signal-aleph.core
  (:require [aleph.http :as http]
            [signal.handler :refer [with-handler]])
  (:import [java.lang ProcessHandle]))

(def server (http/start-server
             (constantly {:body "ok"})
             {:port 9999}))

(with-handler :term
  (prn "caught SIGTERM, quitting.")
  (.close server)
  (System/exit 0))

(.exec (Runtime/getRuntime) (format "kill -SIGTERM %s" (.pid (ProcessHandle/current))))
```

**Comment by KingMob** [comment] 2022-06-19 10:18
@ivarref @arnaudgeiser Pyr looks handy in general, but it doesn't do anything with classloaders, which I suspect is the origin of the problem.

Searching the old issues in pyr turned up https://github.com/pyr/signal/issues/3, which led to https://github.com/riemann/riemann/pull/951, where they do something similar to what we do with `manifold.executor/thread-factory`: set the classloader if the current one isn't Clojure's.

An interesting wrinkle is we're not doing quite the same thing in `aleph.netty/wrap-future`. Instead, we push a thread binding for `clojure.lang.Compiler/LOADER`, but that's *not* the same thing as setting the thread's classloader.

I started digging thru the old issues, and this overlaps heavily with #365. It might even be the same, since the exception is not happening on the Signal thread, as I had originally thought, but on a Netty FastThreadLocalThread.

In his comment [here](https://github.com/clj-commons/aleph/issues/365#issuecomment-436829187), he shows that binding `*use-context-classloader*` to false fixes the issue, and I can verify it works in this case, too. I'm unsure if we should rely on it, though. I think it only works because we directly invoke `RT/baseLoader` first. Any use of `RT/makeClassLoader` rebinds it to true, which happens whenever you compile or `eval`, so it feels very fragile to rely on that.

However, I've tried several other options, and none of them appear to work, unfortunately. Oleksii's PR #425 was meant to fix this very similar problem, but doesn't work here, obviously. Manually setting the classloader inside `wrap-future`'s `operationComplete` also doesn't work, weirdly. Nor does the `ensure-dynamic-classloader` fn from the Riemann issue above. 

I'm going to take a break for the moment. If anyone wants to see my expts so far, lmk and I'll share the code.

**Comment by KingMob** [comment] 2022-06-19 15:04
@ivarref @arnaudgeiser OK, I have a fix, kind of.

Riemann already dealt with some similar classloader issues, around the same time, so I suspect Oleksii may have used their initial solution. It would explain why he pushes a frame binding for `clojure.lang.Compiler/LOADER` in `wrap-future`. However, that's not what we do elsewhere, and Riemann replaced their own binding of LOADER not too long after in riemann/riemann#951. 

The fix I have that seems to work is to *remove* our binding of `clojure.lang.Compiler/LOADER`, and add a call to Riemann's `ensure-dynamic-classloader` in `operationComplete`. 

This makes [ivarref/aleph-shutdown-stacktrace](https://github.com/ivarref/aleph-shutdown-stacktrace) close nicely with a SIGINT, but I can't reproduce the error in a unit test with a raised signal. Hell, I still don't have an explanation for why aleph-shutdown-stacktrace fails when sent a SIGINT, but stops cleanly if it simply times out. In both cases, the same fn should be called, that then triggers another fn to run elsewhere on a Netty thread.

I'll make a PR with my change, but I'd be a *lot* happier if we could create a reliably failing unit test. I also need to check the JVM versions. I did all this on Java 17, but a number of the comments in the linked projects talked about differences in behavior based on Java version.

**Comment by ivarref** [comment] 2022-06-19 18:29
Great work @KingMob !

For unit testing, _maybe_ it could be possible to use containers to do the testing?

There is [clj-test-containers](https://github.com/javahippie/clj-test-containers) for example.
It has for example [execute-command!](https://github.com/javahippie/clj-test-containers#execute-command), I suppose this could be used to send the SIGINT using `kill` or so.
I suppose you could also easily tweak a Dockerfile with various JVM versions as well.

**Comment by arnaudgeiser** [comment] 2022-06-20 11:28
Actually, the following lines are enough to trigger the `NoClassFoundError` :

```clojure
(ns signal-aleph.core
  (:require [aleph.http :as http]
            [signal.handler :refer [with-handler]]
            [clojure.test :refer [deftest is]])
  (:import [java.lang ProcessHandle]))

(deftest classpath-test
  (let [server (http/start-server
                (constantly {:body "ok"})
                {:port 9999})]
    (with-handler :term
      (.close server))
    (.exec (Runtime/getRuntime) (format "kill -SIGTERM %s" (.pid (ProcessHandle/current))))))
```

The open question is how to catch it and how to apply the assertion.
Maybe that part could be extracted on a macro (to ensure it's always inlined) that we redef for the purpose of the test.  [1]
Please let me the evening to cook something around it, even if it won't eventually get merged.

[1] : https://github.com/clj-commons/aleph/blob/master/src/aleph/netty.clj#L221-L234

**Comment by KingMob** [comment] 2022-06-21 06:36
I think we should try and keep the signal the same for testing, i.e., use SIGINT over SIGTERM. SIGTERM is less polite and intended for termination, and the JVM could legitimately decide to halt the process. I haven't checked what other handlers are there, but we should plan to work around them.

**Comment by arnaudgeiser** [comment] 2022-06-30 07:13
Fixed by : https://github.com/clj-commons/aleph/pull/604

**Closed** 2022-06-30 07:13 UTC

**Comment by KingMob** [comment] 2022-07-07 05:23
Pasting from Slack convo with Arnaud for future reference:

=============================================

OK, I think I finally understand what was going wrong in the original code.

First, it has nothing to do with the netty side at all. The stacktrace for the `operation-complete` callback, the thread context classloaders, etc, is identical.

It hinges entirely on the fact that `wrap-future` is called from different threads, one signal, one normal. This means the `class-loader` variable being set for the callback gets different thread context classloaders. My error was in not understanding the hierarchical nature of classloaders correctly.

I got confused because the signal thread sets a Clojure DynamicClassLoader, and the normal thread only sets the AppLoader/PlatformLoader chain. This seems backwards, right? How can Clojure code load without the Clojure DynamicClassLoader?

The thing is, the class not being found is `clojure.lang.PersistentArrayMap`, which is a Java class, not Clojure code. The reason it fails in the signal case is because the DynamicClassLoader’s parent is null, which is the bootstrap loader. Without the AppLoader in its parent chain, it can’t find normal java classes.

(Incidentally, the normal version has the AppLoader, but not the DynamicClassLoader in its context loader, but that’s probably not a problem because Clojure adds it to the stack frames for its own use on demand).

It’s not too different really, from what Riemann’s maintainers found, just confusing because it seemed like it should have been working.
