### ISSUE TITLE
Heap exhaustion with ByteArrayInputStreams

### ISSUE THREAD

**Issue by thomascothran** [clj-commons/aleph#523] opened 2019-09-13 23:05 UTC
When Aleph is passed a ByteInputArrayStream body and there is a client polling that endpoint, memory will increase until the heap is exhausted. I've put together a repro case [here](https://github.com/thomascothran/memory-leak-repro).

Here's a quick way to reproduce this at the repl:

```
(require '[aleph.http :as http])
(require '[clojure.data.json :as json])
;; create a large map and def it as `some-big-map`

(defn handler
  [req]
  {:status 200
   :body (ByteArrayInputStream. (.getBytes ^String (json/write-str some-big-map)))})

(http/start-server handler {:port 9000})
```
Use `wrk` to hit the server repeatedly and you will see something like:

![alephMemoryLeak](https://user-images.githubusercontent.com/17090373/64899261-94988380-d658-11e9-8643-9a7ee3c233b3.png)

I bumped into using Muuntaja's default settings with Alpeh. Tweaking those settings (specifically setting `:return` to `:bytes`) prevented this problem. Initially I thought it was a Reitit/Muuntaja issue, but @ikitommi pointed out that it is tied to the input streams not closing for some reason.

This affects both the latest stable version of Aleph and the latest alpha.

**Comment by KingMob** [comment] 2022-03-22 17:36
@thomascothran I may have a solution, if you're still interested. I'm still learning netty and aleph, but based on my YourKit profiling, the issue is a reference to the ByteArrayInputStream is being held in the channel's closing listener in `send-streaming-body`:

```clojure
(if (s/stream? body')
  (s/close! body')
  (s/close! src))
```

In our problem case, `body'` is the BAIS, and doesn't need closing, but the listener is general, so it holds onto it so it can check if it's a stream. My immediate solution was to to check if `body'` is a stream earlier, return the `if` branches as fns, and use _that_ as the handler. This way, `body'` is only closed over if actually needed:

```clojure
(if (s/stream? body')
  #(s/close! body')
  #(s/close! src))
```

This fixes your OOME in my testing, but I don't know yet why the netty channels themselves are not being closed. I think it's because the HTTP channels are being kept alive by default, so any cleanup that would happen when the channel itself ends may be hundreds of requests later. But I'm confused as to why, if channel closing is the wrong time to free up some of these resources, it hasn't been noticed earlier. I think we can be smarter and more aggressive with freeing resources, but I need to look further. Might need to ping Zach on this one.

Regardless, if you're willing to take another look (three years later), I'll happily push a branch with the fix for you to test with.

**Closed** 2022-03-29 05:57 UTC
